مimport time
import sys

def  delay_print(s):
    for c in s:
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(0.005)
delay_print
print("\033[1;31m@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&BGPPP5PGGGB#&@@@@@&@@@&@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@&B5J?777!?7J?YPPYJ5G&@@&@@@&@@@&&@@@@@@@@@@@&@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@&@GY77777?JPGB#BGP5Y5JJG&&#&@&#@@&#&@@@@@@@@&@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@&&@@@B??777JP#&&&##&&5JY5JG####&&##&&#&@@@&@&&@&@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@&@@@&&&G5??77J#&&#&###&5JJY5P&#&&&&&&&&###&&&&@@&&@@@@@&@@&&@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@&&&@@&YYY777G&#######&GYY5PP##BBGGGGGB#&####@@&&@@@&&&@@@@@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@@@@@@&&&#JJPY775&########&BBG55YYYJYYJJJJY5B&&####@@@&&&@@@&&@@@@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@&@@@@@&&@&&&5J5P5J?P#&######&BY?7????JYYJJJYYYJ5#####&&#&&&&&&@@@@@&&@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@&&&@@&&&&&&#5JY5YYJ5B#&@&&&&J!JGGP5P5?JYYYJJJYJJ5######&&&&@@&&&&&@@@@@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@@@@&&&&&&#####5J5JJJJJYPGGBBBP?JGPYG5JJJY5G5YJJJJJ5##&#####&&&&&&&&@@@&@@@@@@@@@@@@@")
print("@@@@@@@@@@@@@@@@&&&&&&&####&###PYJYJJJJJJY5YJJ5Y555BJ!!77JPPP5GYY5G######&####&&&&&@@@@@&&@@@@@@@@@@")
print("@@@@@@@@@@@@&&&&&&&&&#&###&&&##&&#BGG5YJJJ55JJJJYY5PP5GGY7?B##BG#&&&###########&@@&&&&&@@@@@@@@@@@@@")
print("@@@@@@@@@&&@@@@&&##&&#&##########&&#&#BP55YYY5PGG5JJY5GB#Y!B&&&&&#####&###&########&@@@@@@@@@@@@@@@@")
print("@@@@@@@@@&&&&&&&&#####&&####&#########&&&&##&&&&&&#BYYYPBPJPPPGGG####&&###&&&&&###&&&#&&&@@&@@@@@@@@")
print("@@@@@@@@@&@@&##&#&#BBGGGPPPGBB&&############&#&##&&&#JJYYPGP5BBBBP#&&#GGGPGGGGBB##&&##&&&&@&@@@@@@@@")
print("@@@@@@@@@&&&&###BGGGGBPGGGBPPPP#######&&###&&###&BB&#J7?5J5YP&&BPG#&B55PPBGGGPGPGGGBB###&&@@@@@@@@@@")
print("@@@@@@@@@&&#GGGGBBB#BBBGBBB#GGPP&#####&#######&&P7JG577!55JY#&&BGB#&PPGB#BB#B##B#GBBGGGB&@&&@@@@@@@@")
print("@@@@@@@@@&#GBB#BBGBGBGBGGGBGBBPPB&&&#######&&##5777?PG5?GBPB&##&&&&GPPBBBBGGGBGBBBBGB#GBGB&@@@@@@@@@")
print("@@@@@@@@&BPB#GGBP#GG#G#BBPPBBBGPPGG#&&&##&###GY7?5Y7?PBGB##&&&&&#GPPPB#GBGGGGBGBGG#PBGB#GGB&&&@@@@@@")
print("@@@@@@@#GB#GG###G#BG#PPBGGBGGGBGGGPPPB###GPGGJ7JGGG5??YBGPG####GP5GPBBGGGBGGBGB#GG#BBBBBPBGG&@@@@@@@")
print("@@@@@@&B#BBB###PGGGPGPPGPG#PBGBBBBGGPGPGGG#B?7YGP5PG5?7JBGGPPPPPPGGBBBPBG#PGBGGBPGBGGBB#BBGBB#@@@@@@")
print("@@@@@@#B#GB#BBBGP5B5YBBYBG5GBBGGBBBGG#GGG#G?7YGP5P5PGGJ7JGBBGGBBGBBBPBBBGGG#5GBP5BPPBGGBBBGBB#&@@@@@")
print("@@@@@&#&B#BBGG5BBG#BPB#G#BPB5BBBGPGBB####P?75GP55YYPPGGJ7?G@&####GPGGBBPBPGBGBGPGBGPB55BGGBGG&#@@@@@")
print("@@@@@###BBGB5#BB#BB#BB#BB#BBB#B#GBPGGB##57?5GP5PYYYYPPPGY77P##GGBPGGBBBGBB#BBBPBBGBBGPGG5BGG#BB&@@@@")
print("@@@@@BBGG5GBGBGG#BBBPGBBBGGBB&BGGBB###&Y7?PG55YYJYYJYY5PG577Y&&B#BBBGBBBBBGGGBGPBGGGGG#BP#PPBBB#@@@@")
print("@@@@@&GP#GBGGBGG#B#5PPP#GPBPB&PPBBBBBBY7?GG5YYYY5Y5Y5YY55GP?7J#&BBBGB5BB5GP5BPPPPG#BGP#GGBBBBP#&@@@@")
print("@@@@@&B#BGBG#BGPBG#PB5G#BBBG##BBBP##GJ7JGP55555Y5555Y5Y5Y5PGJ7?GB#GGBGBBGBGGBPYBPBBPGPBGGGGB#BB@@@@@")
print("@@@@@@BBBGBP&GBPPGBBGGBBPBBGBB###P@G?7YBPY555GB###B##BPP55JPGY??P&GPB#GBB#GGBGBBBBB5PPBGBPGGBB#@@@@@")
print("@@@@@@G#BBGP#G5GY##G5BBBGBGGBB#B##P775GPYPPY55BJ?BG&@#GGJ55YPG57?5##BGG#BGBGBPBGGG#PYB5GB5PGG#&@@@@@")
print("@@@@@@##PPG5#G5#G#BB5BBBGBGBGBBB#5775G55GY7!JJYY5#@&#G55!7YG55GP?7Y&BGBGBGBGBGBPP#BGG#YGBYGPG#&@@@@@")
print("@@@&&@#BBGGB#GGBP#GB#GBBGBGBGBB#57?PGYJ5G?7!7JYPG##G55Y7!7Y55YYGPJ7JBBBPGGGGBBPBBBBGBBGGBPBGB#&@@@@@")
print("@@@@@@&GB#PGBGGGP#PGG5GPGGPBPG#Y7JGGYJJJY55J????JYYJJ?7?Y5P55YJYGGJ7?GB5GGPBBBPBBPBGGBPPBGG##B&@@@@@")
print("@@@@@@@GBBPGBGGGBBPGGPGPPGY#BGJ7JGGYJJYYYJYYYYYYYYY5Y5555Y55YJYY5GGY7?PP#P5GGGPPBPGGPB5PBPGGGB@@@@@@")
print("@@@@@@&GGBPGBGGBGGPBP5P5G&#&B?7YGP5YYJJJJY5YYYYYYYYYYY55YJJJYYYY55PB5?75&&G#5GGPGPGGPBPPBPGGG#@@@@@@")
print("@@@@@@@BBGGBGPBGGGPGGYGP#&&P775GP5YYYYYYYYYYYYYY5YYYYYYYJYYYYY5555PPGP?7Y#&&BGPPGPPGPG5PGPGGB#@@@@@@")
print("@@@@@@@#GGPP5PBPGGP5#G&&&&57?PBP5GP55555P555555555555555YY5555P55PG55GGJ7?B&&&BGB5G5PPPPGPGGB&@@@@@@")
print("@@@@@@&#GGGPPPGPG#PB&&&&#J77YPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPGP5J7?G&&&#&G#55GG5P5GGG&@@@@@@")
print("@@@@@@@#GBGGGPGG5BB#&&&#J7?J??????7???????7???7????7???????????????????J????P&&&&##G5PGPPPPPG&@@@@@@")
print("@@@@@@@#GGGBPPGGG#&#&#BBB#PPGJB#BB###############B#BBB#BB###BBBBGGGGGGB####BB&&&##&BGPGPGGPGG#@@@@@@")
print("@@@@@@&GPGGBPPGB###&#GGGPP7?J7G&&&&&&&&&&&&&&&&&&&&&&&&&##BGBPGGPYYYYJY5G#&@@&####&&&BGPPGPBGB@@@@@@")
print("@@@@@@&BPGPBPPG#&##&5555JJ77?5#&######&#&###&####&&&##B5YJJJYYP5JJJYYJJJ?Y5P#&&#&&##&BPPPGPGGB&@@@@@")
print("@@@@@@@#PGPBPPG###&BY57??777JB&################&&&BPP5YJJJJYJYYYJYJJ?JJJY??JY5P#&#####55PG5GGB&@@@@@")
print("@@@@@@&BGGPGGGB###&G5J?77777J#&##&#####&####&&#GYJ55P5YYYJJYJJYJ?Y5YY55YYJJJ55JYB&###&P5PPPGBB&@@@@@")
print("@@@@@@BGGPPP#G#####&J77!!777J5&@&######&#&&#G5J?JP55YYYYYJJYY5PGGBBBGP5YYYYYYYJ?J#####BP#PGPBB#@@@@@")
print("@@@@@&#GPB5G&B###&&@G7??7!777?YG###&&####GP?7?Y5YJJJYJJJYYG##&&&&&&##&#GJ?7?JJ555G&###&B&PPGGG#@@@@@")
print("@@@@@&@5##YB&&#&&&##&G?7777!!!77?JJYY5YJ?!77Y5YJJJY5YYPG##&##&&###&####&BJ77!??YGB&#####&BYBG5&@@@@@")
print("@@@@@@#P@G5&##&&&&###&BJJ7!77!!!!!7!77!77?5P5JJJJ5PBB#&&###############&#YJ777?7Y#&&#&##&&5B@P#@@@@@")
print("@@@@@&G@&P##&&&&&&&##&&&BJJ7!!??!?7!!77JPPP5YJ5PB##&###################&BYJ?777?J&@&####&&#G@&B@@@@@")
print("@@@@@&@@##@&&#&&&&&&&&#&&&#5??77!???JYYYY55GG##&&&###############&##&&&#YJ7?77?JB&#&###&@@@B#@@@@@@@")
print("@@@@@@@@&&&&#&&&&&&#&&&&&&&&&#GGBGGGPPGBB###&##############&##&&##&##B5?777JJJP&&&#####&&&@@B&@@@@@@")
print("@@@@@@@@@&@&#&&&&&&&&&&&&&&&#&&&&&&&&&&&&######BBBGGGBBBB##&&&&&#BP5JJJ555PY5B&#####&##&@@@@@@@@@@@@")
delay_print("\033[1;92m               Developed by: '\033[1;91mqorsan\033[1;93mtaiz\033[1;92m'   v_1.00           \033[1;92m")
print('\033[1;92m')
